Add passthrough capability, manpage

diff --git a/twilio/txtnotify b/twilio/txtnotify
--- a/twilio/txtnotify
+++ b/twilio/txtnotify
@@ -1,25 +1,26 @@
 #!/bin/bash
 function usage {
-    echo "Usage: $0 [-t to-number] [-d callerid] [-q] [message]"
+    echo "Usage: $0 [-t to-number] [-d callerid] [-q] [-p] [message]"
     exit 1
 }
 
-while getopts ":t:d:q" opt; do
+while getopts ":t:d:q:p" opt; do
     case "$opt" in
         t) TO_NUMBER=$OPTARG;;
         d) CALLERID=$OPTARG;;
         q) QUIET=1;;
+        p) PASSTHROUGH=1;;
         *) echo "Invalid argument: $opt"; usage;;
     esac
 done
 
 if [ ! -f "$HOME/.twiliorc" ]; then
-    echo "Error: $HOME/.twiliorc not found"
+    echo "Error: $HOME/.twiliorc not found" >&2
     exit 1
 fi
 
 if [ ! -f "$HOME/.twilio.key" ]; then
-    echo "Error: $HOME/.twilio.key not found"
+    echo "Error: $HOME/.twilio.key not found" >&2
     exit 1
 fi
 
@@ -43,5 +44,9 @@ AUTHTOKEN=$(cat $HOME/.twilio.key)
 
 RESPONSE=$(curl -fSs -u "$ACCOUNTSID:$AUTHTOKEN" -d "From=$CALLERID" -d "To=$TO" -d "Body=$MSG" "https://api.twilio.com/2010-04-01/Accounts/$ACCOUNTSID/SMS/Messages" 2>&1)
 if [ $? -gt 0 -a -z "$QUIET" ]; then
-    echo "Failed to send SMS to $PHONE: $RESPONSE"
+    echo "Failed to send SMS to $PHONE: $RESPONSE" >&2
+fi
+
+if [ -n "$PASSTHROUGH" ]; then
+    echo $(cat)
 fi
